/**
 * E2E 视觉回归测试运行器
 */
const automator = require('miniprogram-automator');
const config = require('../config');
const ScreenshotComparator = require('../utils/comparator');
const ReportGenerator = require('../utils/report');
const LayoutAssertions = require('../utils/assertions');

class TestRunner {
  constructor() {
    this.comparator = new ScreenshotComparator();
    this.report = new ReportGenerator();
    this.assertions = null;
    this.miniProgram = null;
    this.updateBaseline = process.env.UPDATE_BASELINE === 'true';
  }
  
  /**
   * 启动开发者工具
   */
  async launch() {
    console.log('🚀 启动微信开发者工具...');
    console.log(`📁 项目路径: ${config.projectPath}`);
    
    this.miniProgram = await automator.launch({
      projectPath: config.projectPath,
      cliPath: config.devtoolPath
    });
    
    this.assertions = new LayoutAssertions(this.miniProgram);
    console.log('✅ 开发者工具已启动');
  }
  
  /**
   * 注入 mock 数据
   */
  async injectMockData(scenario) {
    console.log(`🎭 注入场景数据: ${scenario}`);
    
    await this.miniProgram.evaluate(() => {
      // 启用 mock 模式
      wx.setStorageSync('e2e_mock_enabled', true);
      
      // 清空现有数据
      wx.removeStorageSync('e2e_mock_ocp_tasks');
      wx.removeStorageSync('e2e_mock_ocp_time_templates');
      wx.removeStorageSync('e2e_mock_ocp_day_states');
    });
    
    const scenarioData = config.mockData.scenarios[scenario];
    
    if (scenario === 'heavy') {
      // 生成 heavy 场景的详细数据
      await this.generateHeavyData();
    } else {
      // 注入普通场景数据
      await this.miniProgram.evaluate((data) => {
        if (data.tasks) {
          wx.setStorageSync('e2e_mock_ocp_tasks', data.tasks);
        }
        if (data.templates) {
          wx.setStorageSync('e2e_mock_ocp_time_templates', data.templates);
        }
      }, scenarioData);
    }
    
    console.log('✅ Mock 数据已注入');
  }
  
  /**
   * 生成 heavy 数据
   */
  async generateHeavyData() {
    const today = new Date();
    const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
    
    await this.miniProgram.evaluate((dateStr) => {
      const tasks = [];
      const schedule = [];
      
      for (let i = 0; i < 20; i++) {
        const startHour = 9 + Math.floor(i / 3);
        const startMin = (i % 3) * 20;
        const minutes = [30, 45, 60][i % 3];
        
        tasks.push({
          id: `e2e_mock_task_${i}`,
          title: `测试任务 ${i + 1} - ${['整理', '阅读', '写作', '会议', '学习'][i % 5]}`,
          category: ['工作', '学习', '生活'][i % 3],
          minutes,
          isFixed: i < 3,
          startTime: i < 3 ? `${String(startHour).padStart(2, '0')}:${String(startMin).padStart(2, '0')}` : null,
          endTime: i < 3 ? `${String(startHour).padStart(2, '0')}:${String(startMin + minutes).padStart(2, '0')}` : null,
          status: i < 5 ? 'done' : i < 10 ? 'scheduled' : 'todo',
          priority: ['high', 'mid', 'low'][i % 3],
          createdAt: new Date().toISOString()
        });
        
        schedule.push({
          id: `e2e_mock_sched_${i}`,
          taskId: i < 15 ? `e2e_mock_task_${i}` : null,
          kind: i < 15 ? 'task' : 'break',
          title: i < 15 ? `测试任务 ${i + 1}` : '休息',
          start: `${String(startHour).padStart(2, '0')}:${String(startMin).padStart(2, '0')}`,
          end: `${String(startHour).padStart(2, '0')}:${String(startMin + minutes).padStart(2, '0')}`,
          minutes,
          status: i < 5 ? 'done' : i < 10 ? 'scheduled' : 'todo',
          isAutoGenerated: true
        });
      }
      
      wx.setStorageSync('e2e_mock_ocp_tasks', tasks);
      
      const dayStates = {
        [dateStr]: {
          date: dateStr,
          scheduleItems: schedule,
          notDoneReasons: []
        }
      };
      wx.setStorageSync('e2e_mock_ocp_day_states', dayStates);
      
      wx.setStorageSync('e2e_mock_ocp_time_templates', [
        { id: 'e2e_mock_tmpl_0', start: '09:00', end: '12:00', label: '上午工作' },
        { id: 'e2e_mock_tmpl_1', start: '14:00', end: '18:00', label: '下午工作' },
        { id: 'e2e_mock_tmpl_2', start: '20:00', end: '22:00', label: '晚间学习' }
      ]);
    }, dateStr);
  }
  
  /**
   * 清空 mock 数据
   */
  async clearMockData() {
    console.log('🗑️ 清空 mock 数据...');
    await this.miniProgram.evaluate(() => {
      wx.removeStorageSync('e2e_mock_enabled');
      wx.removeStorageSync('e2e_mock_ocp_tasks');
      wx.removeStorageSync('e2e_mock_ocp_time_templates');
      wx.removeStorageSync('e2e_mock_ocp_day_states');
    });
  }
  
  /**
   * 测试单个页面场景
   */
  async testPageScenario(pageName, scenario) {
    const pageConfig = config.pages[pageName];
    const screenshotName = `${pageName}_${scenario}.png`;
    
    console.log(`\n📸 测试: ${pageName} - ${scenario}`);
    
    try {
      // 注入 mock 数据
      await this.injectMockData(scenario);
      
      // 切换 tab
      const page = await this.miniProgram.switchTab(pageConfig.path);
      await this.miniProgram.sleep(config.timeouts.navigate);
      
      // 等待渲染稳定
      await page.waitFor('.page-container', config.timeouts.render);
      await this.miniProgram.sleep(500);
      
      // 执行页面特定操作
      await this.performPageActions(page, pageName, scenario);
      
      // 截图
      const screenshot = await page.screenshot();
      await this.comparator.saveScreenshot(screenshot, screenshotName, 'current');
      
      // 执行布局断言
      const assertions = await this.runAssertions(page, pageName, scenario);
      
      // 对比截图
      let comparison = null;
      if (!this.updateBaseline) {
        comparison = await this.comparator.compare(screenshotName, screenshotName);
      }
      
      // 更新基线（如果需要）
      if (this.updateBaseline) {
        await this.comparator.updateBaseline(screenshotName);
        console.log('  ✅ 基线已更新');
      }
      
      // 记录结果
      const passed = this.updateBaseline || 
                     (comparison && comparison.matched && assertions.every(a => a.passed));
      
      this.report.addResult({
        page: pageName,
        scenario,
        screenshot: screenshotName,
        passed,
        comparison,
        assertions,
        error: passed ? null : (comparison?.reason || assertions.find(a => !a.passed)?.message)
      });
      
      console.log(`  ${passed ? '✅' : '❌'} ${passed ? '通过' : '失败'}`);
      
    } catch (error) {
      console.error(`  ❌ 错误: ${error.message}`);
      this.report.addResult({
        page: pageName,
        scenario,
        screenshot: screenshotName,
        passed: false,
        error: error.message
      });
    }
  }
  
  /**
   * 执行页面特定操作
   */
  async performPageActions(page, pageName, scenario) {
    switch (pageName) {
      case 'today':
        if (scenario === 'heavy') {
          // 滚动到底部
          await page.scrollTo(0, 99999);
          await this.miniProgram.sleep(1000);
        }
        break;
        
      case 'schedule':
        if (scenario === 'heavy') {
          // 滚动到列表底部
          await page.scrollTo(0, 99999);
          await this.miniProgram.sleep(1000);
        }
        break;
        
      case 'tasks':
        if (scenario === 'heavy') {
          // 检查底部按钮
          await this.miniProgram.sleep(500);
        }
        break;
        
      case 'review':
        if (scenario === 'normal') {
          // 等待今日复盘输入框
          await page.waitFor('.reflection-card', 2000);
        }
        break;
    }
  }
  
  /**
   * 运行布局断言
   */
  async runAssertions(page, pageName, scenario) {
    const assertions = [];
    
    // Tabbar 遮挡检查
    if (scenario === 'heavy') {
      const lastItemResult = await this.assertions.assertLastItemVisible('.timeline, .task-list');
      assertions.push({
        name: '最后一项可见',
        ...lastItemResult
      });
    }
    
    // 页面特定断言
    switch (pageName) {
      case 'tasks':
        if (scenario === 'heavy') {
          const buttonResult = await this.assertions.assertFixedButtonVisible('.bottom-action__btn');
          assertions.push({
            name: '底部按钮可见',
            ...buttonResult
          });
        }
        break;
        
      case 'review':
        const capsuleResult = await this.assertions.assertTabbarCapsuleCentered();
        assertions.push({
          name: 'Tabbar 胶囊居中',
          ...capsuleResult
        });
        break;
    }
    
    return assertions;
  }
  
  /**
   * 运行所有测试
   */
  async runAll() {
    console.log('='.repeat(60));
    console.log('🎯 开始视觉回归测试');
    console.log('='.repeat(60));
    
    try {
      // 启动
      await this.launch();
      
      // 测试每个页面的每个场景
      for (const [pageName, pageConfig] of Object.entries(config.pages)) {
        console.log(`\n📄 测试页面: ${pageName}`);
        
        for (const scenario of pageConfig.scenarios) {
          await this.testPageScenario(pageName, scenario);
        }
      }
      
      // 生成报告
      const reportPath = this.report.generateHTML();
      const stats = this.report.generateConsole();
      
      console.log(`\n📊 详细报告: ${reportPath}`);
      
      // 返回测试结果
      return {
        success: stats.failed === 0,
        stats,
        reportPath
      };
      
    } catch (error) {
      console.error('❌ 测试运行失败:', error);
      throw error;
      
    } finally {
      // 清理
      await this.clearMockData();
      
      // 关闭开发者工具
      if (this.miniProgram) {
        await this.miniProgram.close();
        console.log('\n👋 开发者工具已关闭');
      }
    }
  }
}

// 运行测试
if (require.main === module) {
  const runner = new TestRunner();
  runner.runAll()
    .then(result => {
      process.exit(result.success ? 0 : 1);
    })
    .catch(error => {
      console.error(error);
      process.exit(1);
    });
}

module.exports = TestRunner;
