/**
 * Mock 数据管理器
 */
const config = require('../config');

class MockDataManager {
  constructor() {
    this.namespace = config.mockData.namespace;
    this.enabled = false;
  }
  
  /**
   * 启用 Mock 模式
   */
  enable() {
    this.enabled = true;
    console.log('🎭 Mock 模式已启用');
  }
  
  /**
   * 禁用 Mock 模式
   */
  disable() {
    this.enabled = false;
    console.log('🎭 Mock 模式已禁用');
  }
  
  /**
   * 清空 Mock 数据
   */
  clear() {
    const keys = wx.getStorageInfoSync().keys;
    keys.forEach(key => {
      if (key.startsWith(this.namespace)) {
        wx.removeStorageSync(key);
      }
    });
    console.log('🗑️ Mock 数据已清空');
  }
  
  /**
   * 注入场景数据
   */
  inject(scenarioName) {
    if (!this.enabled) {
      console.warn('Mock 模式未启用');
      return;
    }
    
    const scenario = config.mockData.scenarios[scenarioName];
    if (!scenario) {
      console.error(`未知场景: ${scenarioName}`);
      return;
    }
    
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0');
    const day = String(today.getDate()).padStart(2, '0');
    const dateStr = `${year}-${month}-${day}`;
    
    // 注入任务数据
    if (scenario.tasks) {
      const tasks = scenario.tasks.map((task, index) => ({
        ...task,
        id: `${this.namespace}task_${index}`,
        createdAt: new Date().toISOString()
      }));
      wx.setStorageSync(`${this.namespace}ocp_tasks`, tasks);
    }
    
    // 注入模板数据
    if (scenario.templates) {
      const templates = scenario.templates.map((tmpl, index) => ({
        ...tmpl,
        id: `${this.namespace}tmpl_${index}`
      }));
      wx.setStorageSync(`${this.namespace}ocp_time_templates`, templates);
    }
    
    // 注入排程数据
    if (scenario.schedule) {
      const dayStates = wx.getStorageSync(`${this.namespace}ocp_day_states`) || {};
      dayStates[dateStr] = {
        date: dateStr,
        scheduleItems: scenario.schedule,
        notDoneReasons: []
      };
      wx.setStorageSync(`${this.namespace}ocp_day_states`, dayStates);
    }
    
    console.log(`✅ 场景数据已注入: ${scenarioName}`);
  }
  
  /**
   * 生成 heavy 场景的详细数据
   */
  generateHeavyData() {
    const tasks = [];
    const schedule = [];
    
    // 生成 20 个任务
    for (let i = 0; i < 20; i++) {
      const startHour = 9 + Math.floor(i / 3);
      const startMin = (i % 3) * 20;
      const minutes = [30, 45, 60][i % 3];
      
      tasks.push({
        id: `${this.namespace}task_${i}`,
        title: `测试任务 ${i + 1} - ${['整理', '阅读', '写作', '会议', '学习'][i % 5]}`,
        category: ['工作', '学习', '生活'][i % 3],
        minutes,
        isFixed: i < 3,
        startTime: i < 3 ? `${String(startHour).padStart(2, '0')}:${String(startMin).padStart(2, '0')}` : null,
        endTime: i < 3 ? `${String(startHour).padStart(2, '0')}:${String(startMin + minutes).padStart(2, '0')}` : null,
        status: i < 5 ? 'done' : i < 10 ? 'scheduled' : 'todo',
        priority: ['high', 'mid', 'low'][i % 3],
        createdAt: new Date().toISOString()
      });
      
      schedule.push({
        id: `${this.namespace}sched_${i}`,
        taskId: i < 15 ? `${this.namespace}task_${i}` : null,
        kind: i < 15 ? 'task' : 'break',
        title: i < 15 ? `测试任务 ${i + 1}` : '休息',
        start: `${String(startHour).padStart(2, '0')}:${String(startMin).padStart(2, '0')}`,
        end: `${String(startHour).padStart(2, '0')}:${String(startMin + minutes).padStart(2, '0')}`,
        minutes,
        status: i < 5 ? 'done' : i < 10 ? 'scheduled' : 'todo',
        isAutoGenerated: true
      });
    }
    
    wx.setStorageSync(`${this.namespace}ocp_tasks`, tasks);
    
    const today = new Date();
    const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
    const dayStates = {
      [dateStr]: {
        date: dateStr,
        scheduleItems: schedule,
        notDoneReasons: schedule
          .filter(item => item.status === 'not_done')
          .map(item => ({
            taskId: item.taskId,
            title: item.title,
            reason: '时间不够，需要延后处理'
          }))
      }
    };
    wx.setStorageSync(`${this.namespace}ocp_day_states`, dayStates);
    
    // 设置模板
    wx.setStorageSync(`${this.namespace}ocp_time_templates`, [
      { id: `${this.namespace}tmpl_0`, start: '09:00', end: '12:00', label: '上午工作' },
      { id: `${this.namespace}tmpl_1`, start: '14:00', end: '18:00', label: '下午工作' },
      { id: `${this.namespace}tmpl_2`, start: '20:00', end: '22:00', label: '晚间学习' }
    ]);
    
    console.log('✅ Heavy 数据已生成（20个任务）');
  }
}

module.exports = MockDataManager;
